# Generated by Django 4.2.6 on 2023-10-28 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_blogsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_hacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('content', djrichtextfield.models.RichTextField(max_length=3000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='health_hacks/')),
                ('image_alt', models.CharField(max_length=100)),
                ('hack_type', models.CharField(choices=[('Supplements', 'suplements'), ('Research', 'research'), ('Longevity', 'longevity'), ('Wellness', 'wellness'), ('Meditation', 'meditation'), ('Hot cold therapy', 'hot cold therapy'), ('Sun therapy', 'sun therapy'), ('Diet', 'diet'), ('Exercise', 'exercise')], default='suplements', max_length=50)),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
